image: ghcr.io/olix0r/tcp-echo:v9

reverse: false

client:
  replicas: 1
  linkerdInject: true

server:
  services: 1
  replicas: 1
  linkerdInject: true
  opaque: false

linkerd: {}
  #proxyImage: ...
  #proxyVersion: ...
